homeSuccess:
  layout: layoutA

smtHomeSuccess:
  javascripts: [%OP_JQUERY_URL%, %OP_JQUERYUI_URL%, util]
  layout: smtLayoutGroup

smtEditSuccess:
  layout: smtLayoutGroup

smtMemberListSuccess:
  layout: smtLayoutGroup
